In [37]:
import pandas as pd
import numpy as np

In [38]:
dict1={
    "name":['saurabh','shruti','khushi','sanskar'],
    "marks":[98,99,100,102],
    "city":['pune','bangluru','nagar','pcmc']
}

In [39]:
df=pd.DataFrame(dict1)

In [40]:
print(df.head())

      name  marks      city
0  saurabh     98      pune
1   shruti     99  bangluru
2   khushi    100     nagar
3  sanskar    102      pcmc

In [41]:
df.to_csv('friends.csv')

In [42]:
df.to_csv('friends_noindex.csv',index=False)

PermissionError: [Errno 13] Permission denied: 'friends_noindex.csv'

In [43]:
df.describe()

            marks
count    4.000000
mean    99.750000
std      1.707825
min     98.000000
25%     98.750000
50%     99.500000
75%    100.500000
max    102.000000

In [44]:
data1=pd.read_csv('SM_data.csv')

In [46]:
data1.index=data1['Date']

In [48]:
print(type(data1['SM10']))

<class 'pandas.core.series.Series'>

In [47]:
print(type(data1))

<class 'pandas.core.frame.DataFrame'>

In [49]:
ser=pd.Series(np.random.rand(34))
type(ser)

pandas.core.series.Series

In [50]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
type(newdf)

pandas.core.frame.DataFrame

In [56]:
data=pd.read_csv('SM_data.csv')
data=data.set_index('Date')
data.index = pd.to_datetime(data.index, format='%d-%m-%Y')

In [57]:
data.T

Date,1980-01-01,1980-01-02,1980-01-03,1980-01-04,1980-01-05,1980-01-06,1980-01-07,1980-01-08,1980-01-09,1980-01-10,...,2021-11-12,2021-11-13,2021-11-14,2021-11-15,2021-11-16,2021-11-17,2021-11-18,2021-11-19,2021-11-20,2021-11-21
SM10,17.670000,17.670000,17.480000,17.480000,17.300000,17.300000,17.140000,17.140000,17.000000,17.000000,...,26.390000,25.940000,25.700000,25.940000,33.500000,32.810000,31.610000,31.160000,30.510000,30.230000
SM30,20.133333,20.133333,20.066667,20.066667,20.000000,20.000000,19.933333,19.933333,19.866667,19.866667,...,28.733333,28.466667,28.233333,28.100000,29.266667,31.633333,31.400000,31.133333,30.833333,30.566667
Sm60,21.133333,21.133333,21.066667,21.066667,20.983333,20.983333,20.916667,20.916667,20.850000,20.850000,...,30.083333,29.883333,29.683333,29.516667,29.400000,29.383333,29.533333,29.650000,29.716667,29.733333
SM100,31.370000,31.370000,31.360000,31.360000,31.340000,31.340000,31.320000,31.320000,31.310000,31.310000,...,33.870000,33.790000,33.720000,33.650000,33.590000,33.530000,33.470000,33.420000,33.370000,33.330000
St10,24.150000,24.150000,24.150000,24.150000,23.250000,23.250000,22.850000,22.850000,22.750000,22.750000,...,22.050000,23.450000,24.850000,25.050000,24.750000,24.850000,24.550000,24.750000,24.750000,25.150000
St30,23.350000,23.350000,23.650000,23.650000,23.650000,23.650000,23.450000,23.450000,23.350000,23.350000,...,22.950000,23.150000,23.550000,23.950000,24.250000,24.350000,24.350000,24.350000,24.350000,24.450000
St60,23.450000,23.450000,23.550000,23.550000,23.650000,23.650000,23.650000,23.650000,23.750000,23.750000,...,23.950000,23.850000,23.850000,23.950000,23.950000,24.050000,24.150000,24.150000,24.250000,24.250000
St100,24.450000,24.450000,24.450000,24.450000,24.450000,24.450000,24.350000,24.350000,24.350000,24.350000,...,24.550000,24.450000,24.450000,24.450000,24.450000,24.350000,24.350000,24.350000,24.350000,24.350000
Rain,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.300000,0.000000,7.400000,2.200000,1.800000,0.200000
Air_Temperature,22.290000,22.980000,21.620000,21.420000,23.070000,23.660000,24.030000,24.750000,23.970000,24.310000,...,24.330000,24.700000,26.060000,26.940000,27.220000,27.400000,26.690000,26.990000,26.700000,26.760000
Unnamed: 11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
next1,17.670000,17.480000,17.480000,17.300000,17.300000,17.140000,17.140000,17.000000,17.000000,16.880000,...,25.940000,25.700000,25.940000,33.500000,32.810000,31.610000,31.160000,30.510000,30.230000,29.660000
next2,17.480000,17.480000,17.300000,17.300000,17.140000,17.140000,17.000000,17.000000,16.880000,16.880000,...,25.700000,25.940000,33.500000,32.810000,31.610000,31.160000,30.510000,30.230000,29.660000,29.110000
next3,17.480000,17.300000,17.300000,17.140000,17.140000,17.000000,17.000000,16.880000,16.880000,17.050000,...,25.940000,33.500000,32.810000,31.610000,31.160000,30.510000,30.230000,29.660000,29.110000,28.670000
next4,17.300000,17.300000,17.140000,17.140000,17.000000,17.000000,16.880000,16.880000,17.050000,17.050000,...,33.500000,32.810000,31.610000,31.160000,30.510000,30.230000,29.660000,29.110000,28.670000,28.250000
next5,17.300000,17.140000,17.140000,17.000000,17.000000,16.880000,16.880000,17.050000,17.050000,17.260000,...,32.810000,31.610000,31.160000,30.510000,30.230000,29.660000,29.110000,28.670000,28.250000,27.660000
next6,17.140000,17.140000,17.000000,17.000000,16.880000,16.880000,17.050000,17.050000,17.260000,17.260000,...,31.610000,31.160000,30.510000,30.230000,29.660000,29.110000,28.670000,28.250000,27.660000,27.080000
next7,17.140000,17.000000,17.000000,16.880000,16.880000,17.050000,17.050000,17.260000,17.260000,17.070000,...,31.160000,30.510000,30.230000,29.660000,29.110000,28.670000,28.250000,27.660000,27.080000,26.530000
next8,17.000000,17.000000,16.880000,16.880000,17.050000,17.050000,17.260000,17.260000,17.070000,17.070000,...,30.510000,30.230000,29.660000,29.110000,28.670000,28.250000,27.660000,27.080000,26.530000,26.030000
ref1,17.370000,17.670000,17.670000,17.480000,17.480000,17.300000,17.300000,17.140000,17.140000,17.000000,...,26.950000,26.390000,25.940000,25.700000,25.940000,33.500000,32.810000,31.610000,31.160000,30.510000

In [58]:
data.sort_index

<bound method DataFrame.sort_index of              SM10       SM30       Sm60  SM100   St10   St30   St60  St100  \
Date
1980-01-01  17.67  20.133333  21.133333  31.37  24.15  23.35  23.45  24.45
1980-01-02  17.67  20.133333  21.133333  31.37  24.15  23.35  23.45  24.45
1980-01-03  17.48  20.066667  21.066667  31.36  24.15  23.65  23.55  24.45
1980-01-04  17.48  20.066667  21.066667  31.36  24.15  23.65  23.55  24.45
1980-01-05  17.30  20.000000  20.983333  31.34  23.25  23.65  23.65  24.45
...           ...        ...        ...    ...    ...    ...    ...    ...
2021-11-17  32.81  31.633333  29.383333  33.53  24.85  24.35  24.05  24.35
2021-11-18  31.61  31.400000  29.533333  33.47  24.55  24.35  24.15  24.35
2021-11-19  31.16  31.133333  29.650000  33.42  24.75  24.35  24.15  24.35
2021-11-20  30.51  30.833333  29.716667  33.37  24.75  24.35  24.25  24.35
2021-11-21  30.23  30.566667  29.733333  33.33  25.15  24.45  24.25  24.35

            Rain  Air_Temperature  Unnamed: 11  next1  next2  next3  next4  \
Date
1980-01-01   0.0            22.29          NaN  17.67  17.48  17.48  17.30
1980-01-02   0.0            22.98          NaN  17.48  17.48  17.30  17.30
1980-01-03   0.0            21.62          NaN  17.48  17.30  17.30  17.14
1980-01-04   0.0            21.42          NaN  17.30  17.30  17.14  17.14
1980-01-05   0.0            23.07          NaN  17.30  17.14  17.14  17.00
...          ...              ...          ...    ...    ...    ...    ...
2021-11-17   0.0            27.40          NaN  31.61  31.16  30.51  30.23
2021-11-18   7.4            26.69          NaN  31.16  30.51  30.23  29.66
2021-11-19   2.2            26.99          NaN  30.51  30.23  29.66  29.11
2021-11-20   1.8            26.70          NaN  30.23  29.66  29.11  28.67
2021-11-21   0.2            26.76          NaN  29.66  29.11  28.67  28.25

            next5  next6  next7  next8   ref1
Date
1980-01-01  17.30  17.14  17.14  17.00  17.37
1980-01-02  17.14  17.14  17.00  17.00  17.67
1980-01-03  17.14  17.00  17.00  16.88  17.67
1980-01-04  17.00  17.00  16.88  16.88  17.48
1980-01-05  17.00  16.88  16.88  17.05  17.48
...           ...    ...    ...    ...    ...
2021-11-17  29.66  29.11  28.67  28.25  33.50
2021-11-18  29.11  28.67  28.25  27.66  32.81
2021-11-19  28.67  28.25  27.66  27.08  31.61
2021-11-20  28.25  27.66  27.08  26.53  31.16
2021-11-21  27.66  27.08  26.53  26.03  30.51

[15300 rows x 20 columns]>